-- Seed disclaimer from old system
INSERT INTO disclaimer (id, judul, judul_en, slug, konten, konten_en, is_active, created_at, updated_at)
VALUES (
    'a068ba72-4dc9-4160-930d-0ab42a1f5ab6',
    'disclaimer pembelian v1',
    'purchasing disclaimer v1',
    'disclaimer-pembelian-v1',
    '<h1>PENAFIAN & PERNYATAAN KESETUJUAN PEMBELI</h1><p><strong>Bulky.id</strong> – Platform Likuidasi Surplus & Overstock di Indonesia</p><p>Dengan mengakses dan/atau melakukan pembelian melalui platform <strong>Bulky.id</strong>, pengguna ("Pembeli") dengan ini <strong>menyetujui dan memahami</strong> seluruh ketentuan berikut:</p><h2>1. Sifat Produk dan Transaksi</h2><ul><li>Semua barang yang dijual di Bulky.id merupakan barang likuidasi, surplus, overstock, sisa retur, atau gagal kirim dari mitra logistik dan e-commerce.</li><li>Barang dijual dalam kondisi <em>"apa adanya (as-is)"</em>, tanpa jaminan atau garansi dari Bulky.id atas kondisi, kelengkapan, nilai komersial, kesesuaian merek, fungsi, ataupun umur pakai produk.</li><li>Deskripsi, foto, dan informasi produk bersifat indikatif, tidak selalu menggambarkan kondisi aktual setiap unit.</li><li>Pembelian bersifat final, kecuali ada kesepakatan tertulis dari Bulky.id.</li></ul><h2>2. Tanggung Jawab Pembeli</h2><ul><li>Pembeli menyatakan telah membaca, memahami, dan menyetujui seluruh syarat dan ketentuan Bulky.id sebelum melakukan pembelian.</li><li>Pembeli menerima seluruh risiko yang melekat pada pembelian barang likuidasi.</li><li>Pembeli bertanggung jawab atas penyimpanan, penjualan kembali, penggunaan, dan distribusi lanjutan produk yang dibeli.</li><li>Pembeli wajib mematuhi peraturan perundangan Indonesia termasuk BPOM, SNI, Perlindungan Konsumen, dan Lingkungan Hidup jika produk dijual kembali.</li></ul><h2>3. Pembebasan Tanggung Jawab</h2><ul><li>Bulky.id tidak bertanggung jawab atas kerugian langsung maupun tidak langsung, kehilangan keuntungan, klaim pihak ketiga, cedera, atau kerusakan yang timbul akibat penggunaan, penjualan kembali, atau penyalahgunaan barang yang dibeli.</li><li>Bulky.id tidak bertanggung jawab atas tindakan pihak ketiga termasuk penjual asal, mitra logistik, 3PL, atau platform e-commerce.</li><li>Jika terjadi miss-sort atau kesalahan data, pembeli dapat melapor untuk peninjauan, namun hal tersebut tidak menjadi dasar tuntutan hukum atau kompensasi otomatis.</li><li>Bulky.id tidak menjamin legalitas penjualan kembali produk tertentu di luar wilayah hukum Indonesia.</li></ul><h2>4. Kepemilikan dan Hak Cipta</h2><ul><li>Seluruh merek dan logo adalah milik pemegang haknya masing-masing.</li><li>Bulky.id tidak mengklaim afiliasi dengan merek tersebut kecuali dinyatakan tertulis.</li></ul><h2>5. Ketentuan Hukum</h2><ul><li>Bulky.id beroperasi sesuai hukum Republik Indonesia.</li><li>Setiap perselisihan akan diselesaikan terlebih dahulu melalui musyawarah dan mediasi; apabila tidak tercapai, akan diselesaikan melalui Pengadilan Negeri Jakarta Selatan</li></ul><p><br></p>',
    '<h1>DISCLAIMER & BUYER CONSENT STATEMENT</h1><p><strong>Bulky.id</strong> – Surplus & Overstock Liquidation Platform in Indonesia</p><p>By accessing and/or making purchases through the <strong>Bulky.id</strong> platform, users ("Buyers") hereby <strong>agree and understand</strong> all of the following terms:</p><h2>1. Nature of Products and Transactions</h2><ul><li>All goods sold on Bulky.id are liquidation goods, surplus, overstock, return residue, or failed delivery from logistics and e-commerce partners.</li><li>Goods are sold in <em>"as-is"</em> condition, without any warranty or guarantee from Bulky.id regarding condition, completeness, commercial value, brand suitability, function, or product lifespan.</li><li>Product descriptions, photos, and information are indicative, not always representing the actual condition of each unit.</li><li>Purchases are final, unless there is a written agreement from Bulky.id.</li></ul><h2>2. Buyer Responsibilities</h2><ul><li>Buyers declare that they have read, understood, and agreed to all Bulky.id terms and conditions before making a purchase.</li><li>Buyers accept all risks inherent in purchasing liquidation goods.</li><li>Buyers are responsible for storage, resale, use, and further distribution of purchased products.</li><li>Buyers must comply with Indonesian regulations including BPOM, SNI, Consumer Protection, and Environmental regulations if products are resold.</li></ul><h2>3. Liability Release</h2><ul><li>Bulky.id is not responsible for direct or indirect losses, loss of profits, third party claims, injuries, or damages arising from the use, resale, or misuse of purchased goods.</li><li>Bulky.id is not responsible for the actions of third parties including original sellers, logistics partners, 3PL, or e-commerce platforms.</li><li>If there is a miss-sort or data error, buyers can report for review, but this does not become the basis for legal claims or automatic compensation.</li><li>Bulky.id does not guarantee the legality of reselling certain products outside Indonesian legal jurisdiction.</li></ul><h2>4. Ownership and Copyright</h2><ul><li>All brands and logos are the property of their respective rights holders.</li><li>Bulky.id does not claim affiliation with these brands unless stated in writing.</li></ul><h2>5. Legal Terms</h2><ul><li>Bulky.id operates in accordance with the laws of the Republic of Indonesia.</li><li>Any disputes will be resolved first through deliberation and mediation; if not reached, will be resolved through the South Jakarta District Court</li></ul><p><br></p>',
    true,
    '2025-11-21 23:17:30',
    NOW()
);
