INSERT INTO faq (id, question, question_en, answer, answer_en, urutan, is_active) VALUES
(uuid_generate_v4(), 
 'Apa itu Bulky?', 
 'What is Bulky?', 
 'Bulky adalah platform jual beli barang grosir dengan harga terjangkau.', 
 'Bulky is a wholesale marketplace platform with affordable prices.',
 1, true),
(uuid_generate_v4(), 
 'Bagaimana cara membeli di Bulky?', 
 'How to buy at Bulky?', 
 'Untuk membeli, Anda perlu: 1) Daftar akun, 2) Pilih produk, 3) Checkout, 4) Bayar.', 
 'To buy, you need to: 1) Register, 2) Choose products, 3) Checkout, 4) Pay.',
 2, true),
(uuid_generate_v4(), 
 'Apakah bisa pickup langsung?', 
 'Can I pick up directly?', 
 'Ya, Anda bisa pickup langsung di warehouse kami di Depok.', 
 'Yes, you can pick up directly at our warehouse in Depok.',
 3, true),
(uuid_generate_v4(), 
 'Metode pembayaran apa saja yang tersedia?', 
 'What payment methods are available?', 
 'Kami menerima Bank Transfer, E-Wallet (GoPay, OVO, Dana), QRIS, dan Kartu Kredit.', 
 'We accept Bank Transfer, E-Wallet (GoPay, OVO, Dana), QRIS, and Credit Card.',
 4, true),
(uuid_generate_v4(), 
 'Berapa lama proses pengiriman?', 
 'How long is the delivery process?', 
 'Proses pengiriman biasanya 2-5 hari kerja untuk area Jabodetabek.', 
 'Delivery usually takes 2-5 business days for Jabodetabek area.',
 5, true);
