-- Rollback: Remove multi-lang slug columns from 13 tables

ALTER TABLE blog DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE disclaimer DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE dokumen_kebijakan DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE kategori_produk DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE kategori_blog DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE kategori_video DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE kondisi_produk DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE kondisi_paket DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE label_blog DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE merek_produk DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE produk DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE sumber_produk DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
ALTER TABLE video DROP COLUMN IF EXISTS slug_id, DROP COLUMN IF EXISTS slug_en;
